# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import csv

header = ['nombre', 'empresa calificacion y ciudad', 'descripcion', 'modalidad', 'tiempo']


class TestPrueba1():
  def setup_method(self, method):
    executable_path=r'./chromedriver'
    self.driver = webdriver.Chrome(executable_path=executable_path)
    self.driver = webdriver.Chrome()
    self.vars = {}  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_prueba1(self):
    executable_path=r'./chromedriver'
    self.driver = webdriver.Chrome(executable_path=executable_path)
    with open('vacantes.csv', 'w', encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(header)
        p = 1
        while p <= 100:
            self.driver.get(f"https://co.computrabajo.com/trabajo-de-python?p={p}")
            i = 1
            while i <= 20:
                articulos = self.driver.find_element(By.XPATH, f"//article[{i}]")
                writer.writerow(articulos.text.split('\n'))
                i = i +1
            p = p + 1 

Test = TestPrueba1()
Test.test_prueba1()